# Generated by Django 5.2.17 on 2026-08-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('seminar', 'Seminar Room')], default='lecture', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveIntegerField(help_text='e.g. 100, 200, 300, 400')),
                ('size', models.PositiveIntegerField(help_text='Number of students in the group')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('population_size', models.PositiveIntegerField(default=80)),
                ('max_generations', models.PositiveIntegerField(default=200)),
                ('crossover_prob', models.FloatField(default=0.7)),
                ('mutation_prob', models.FloatField(default=0.2)),
                ('generations_run', models.PositiveIntegerField(default=0)),
                ('best_fitness', models.FloatField(blank=True, null=True)),
                ('hard_violations', models.PositiveIntegerField(default=0)),
                ('soft_violations', models.PositiveIntegerField(default=0)),
                ('execution_seconds', models.FloatField(blank=True, null=True)),
                ('fitness_history', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently published timetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('unit_load', models.PositiveIntegerField(default=2)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('sessions_per_week', models.PositiveIntegerField(default=1, help_text='Number of lecture periods needed per week')),
                ('requires_lab', models.BooleanField(default=False)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='scheduling.lecturer')),
                ('student_groups', models.ManyToManyField(blank=True, related_name='courses', to='scheduling.studentgroup')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period', models.PositiveIntegerField(help_text='Period number within the day (1–8)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': [models.Case(models.When(day='Monday', then=0), models.When(day='Tuesday', then=1), models.When(day='Wednesday', then=2), models.When(day='Thursday', then=3), models.When(day='Friday', then=4), default=5), 'period'],
                'unique_together': {('day', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_index', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.room')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.studentgroup')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetablerun')),
            ],
            options={
                'verbose_name_plural': 'timetable entries',
                'ordering': ['time_slot__day', 'time_slot__period', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=True, help_text='True = preferred slot; False = unavailable / strongly disliked')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduling.lecturer')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_prefs', to='scheduling.timeslot')),
            ],
            options={
                'verbose_name_plural': 'lecturer availabilities',
                'unique_together': {('lecturer', 'time_slot')},
            },
        ),
    ]
